if(NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "Debug integration output missing: ${INPUT}")
endif()
file(READ "${INPUT}" CONTENT)
foreach(KEY IN ITEMS "selection" "outlineVisible" "gpuTimestampAvailable" "gpuUtilizationSource")
    string(FIND "${CONTENT}" "\"${KEY}\"" POSITION)
    if(POSITION LESS 0)
        message(FATAL_ERROR "Debug response does not contain required key: ${KEY}")
    endif()
endforeach()
message(STATUS "Debug schema contains v1.1.2 selection and GPU diagnostics")
