if(NOT EXISTS "${GENERATED}")
    message(FATAL_ERROR "Generated screenshot was not created: ${GENERATED}")
endif()
if(NOT EXISTS "${GOLDEN}")
    message(FATAL_ERROR "Golden screenshot is missing: ${GOLDEN}")
endif()
file(SHA256 "${GENERATED}" GENERATED_HASH)
file(SHA256 "${GOLDEN}" GOLDEN_HASH)
if(NOT GENERATED_HASH STREQUAL GOLDEN_HASH)
    message(FATAL_ERROR "Screenshot does not match the deterministic golden image")
endif()
message(STATUS "Screenshot matches golden image")
